/*
 * File: random.c 
 * --------------
 * This program displays some random numbers
 * generated by random generator function
 * that returns integers that appear to be
 * randomly distribuited in some interval 0 to n,
 * where n is system-dependent.
 */

#include <stdio.h>
#include <stdlib.h>

/* Function prototypes */

int max(int a, int b);
int min(int a, int b);
void printRandomNumbers(int k);

/* Main program */

int main (void) {
   int n;

   printf("Some random numbers will be printed.\n");
   printf("How many would you like to see? ");
   scanf("%d", &n);
   printRandomNumbers(n);

   return 0;
}

/*
 * Funtion: max
 * Usage: int max(int a, int b);
 * -----------------------------
 * Returns the maximum.
 */

int  max(int a, int b) {
  if  (a > b) {
     return a; 
  } else {
     return b;
  }
 
}

/*
 * Funtion: min
 * Usage: int min(int a, int b);
 * -----------------------------
 * Returns the minimum.
 */

int min(int a, int b) {
  if  (a < b ) {
     return a;
  } else {
     return b;
  }

}

/* 
 * Function: printRandomNumbers
 * Usage:int printRandomNUmers(int k);
 * -----------------------------------
 * Returns the random numbers.
 */

void printRandomNumbers(int k) {

   int i, r, biggest, smallest;
   r = biggest = smallest = rand();
   printf("\n%7d", r);
   for (i = 1; i < k; ++i) {
      if (i % 7 == 0)
        printf("\n");
      r = rand();
      biggest = max(r, biggest);
      smallest = min(r, smallest);
      printf("%7d", r);
   }
   printf("\n\n%s%5d \n%s%5d \n%s%5d \n\n", "  Count: ", k, "Maximun: ", biggest,
          "Mininum:  ", smallest);
}
